version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: .docker/frontend/Dockerfile
    container_name: nextjs_container
    ports:
      # node.js/Next.js
      - "8080:8080"
    volumes:
      - "./app/frontend:/home/node/nextjs13-app-directory/frontend/app"
    tty: true
    stdin_open: true
    env_file:
      - .env
    environment:
      - PATH:$SUPABASE_ENVIRONMENT
    platform: linux/arm64/v8
    